export {AlvoCirculo} from './alvo-circulo';
export {AlvoEgo} from './alvo-ego';
export {AlvoElipse} from './alvo-elipse';
export {AlvoHabilidade} from './alvo-habilidade';
export {AlvoLinha} from './alvo-linha';
export {AlvoLosango} from './alvo-losango';
export {AlvoPonto} from './alvo-ponto';
export {AlvoTriangulo} from './alvo-triangulo';
export {AlvoVetor} from './alvo-vetor';