export {GeraArmaBrancaService} from './gera-arma-branca.service';
export {GeraArmaTiroService} from './gera-arma-tiro.service';
export {GeraConsumivelService} from './gera-consumivel.service';
export {GeraEquipamentoService} from './gera-equipamento.service';
export {GeraItemService} from './gera-item.service';
export {GeraMaterialService} from './gera-material.service';
export {GeraMunicaoService} from './gera-municao.service';
export {GeraPosseService} from './gera-posse.service';
export {GeraVestivelService} from './gera-vestivel.service';