export {GeraCarismaService} from './gera-carisma.service';
export {GeraComportamentoService} from './gera-comportamento-service';
export {GeraDeslocamentoService} from './gera-deslocamento.service';
export {GeraDestinoService} from './gera-destino.service';
export {GeraIdentidadeService} from './gera-identidade.service';
export {GeraIndoleService} from './gera-indole.service';
export {GeraReiService} from './gera-rei.service';
export {GeraRespostaService} from './gera-resposta.service';
export {GeraSerService} from './gera-ser.service';